services:
  postgres:
    image: postgres:14
    container_name: lootea_postgres
    environment:
      POSTGRES_DB: lootea_b2b_backend_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
