# Ultra rychlá Brakeman konfigurace
application_path: "."

# Maximální rychlost - minimum kontrol
min_confidence: 1
check_arguments: false
exit_on_warn: false

# Vynechání všech nepotřebných složek
skip_files:
  - "node_modules/**/*"
  - "tmp/**/*"
  - "log/**/*"
  - "coverage/**/*"
  - "vendor/**/*"
  - "db/**/*"
  - "config/**/*"
  - "spec/**/*"
  - "test/**/*"

# Jen nejdůležitější kontroly
only_files:
  - "app/controllers/application_controller.rb"
  - "app/controllers/graphql_controller.rb"
  - "app/models/user.rb"
  - "app/graphql/mutations/login_user.rb"

# Ultra rychlé nastavení
faster: true
parallel_checks: false
timeout: 30

# Jen kritické kontroly
only:
  - SQL
  - CrossSiteScripting
  - MassAssignment
  - Authentication