name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate deployment prerequisites
        run: |
          if [ -z "${{ secrets.RAILWAY_TOKEN }}" ]; then
            echo "❌ RAILWAY_TOKEN not set in secrets"
            exit 1
          fi
          if [ -z "${{ secrets.RAILWAY_SERVICE_ID }}" ]; then
            echo "❌ RAILWAY_SERVICE_ID not set in secrets"
            exit 1
          fi
          echo "✅ All deployment secrets configured"

      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        with:
          service: ${{ secrets.RAILWAY_SERVICE_ID }}

      - name: Deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "🚀 Deployment successful!"
          else
            echo "❌ Deployment failed!"
            exit 1
          fi
